name: Repair
main: JackMD\Repair\Main
version: 1.0.2
api: [3.0.0, 4.0.0]
author: JackMD
website: https://github.com/JackMD/Repair

permissions:
  essentials.repair.use:
    default: true
  essentials.repair.hand:
    default: true
  essentials.repair.all:
    default: true
  repair.sign.create:
    default: op
  repair.sign.break:
    default: op
  repair.sign.place:
    default: op
  repair.sign.use:
    default: op
  repair.sign.use.hand:
    default: op
  repair.sign.use.all:
    default: op
